from Database import *
from VariableByteEncoder import *

database = Database("recipes")

print("Adding ingredients and recipe IDs to database.")
database.AddToIngredientIndexTable("olive oil", 100)
database.AddToIngredientIndexTable("chicken",   100)
database.AddToIngredientIndexTable("spinach",   100)
database.AddToIngredientIndexTable("fish",      200)
database.AddToIngredientIndexTable("chicken",   200)
database.AddToIngredientIndexTable("chicken",   300)
database.AddToIngredientIndexTable("spinach",   300)
database.AddToIngredientIndexTable("corn oil",  400)
database.AddToIngredientIndexTable("corn oil",  200)
database.AddToIngredientIndexTable("oil",       500)
database.AddToIngredientIndexTable("oil",       200)

print("Retrieving recipe IDs from database.")
recipeIds = database.GetRecipeIds("olive oil")
print(recipeIds)
recipeIds = database.GetRecipeIds("chicken")
print(recipeIds)
recipeIds = database.GetRecipeIds("spinach")
print(recipeIds)
recipeIds = database.GetRecipeIds("fish")
print(recipeIds)
recipeIds = database.GetRecipeIds("corn oil")
print(recipeIds)
recipeIds = database.GetRecipeIds("oil")
print(recipeIds)
recipeIds = database.GetRecipeIds("haggis")
print(recipeIds)

print("Adding ingredient synonyms to database.")
database.AddIngredientSynonymsToIngredientIndexTable('olive oil', 'oil,corn oil')
database.AddIngredientSynonymsToIngredientIndexTable('corn oil', 'oil,olive oil')

print("Retrieving ingredient synonyms to database.")
ingredientSynonyms = database.GetIngredientSynonyms('olive oil')
print(ingredientSynonyms)
ingredientSynonyms = database.GetIngredientSynonyms('chicken')
print(ingredientSynonyms)
ingredientSynonyms = database.GetIngredientSynonyms('spinach')
print(ingredientSynonyms)
ingredientSynonyms = database.GetIngredientSynonyms('fish')
print(ingredientSynonyms)
ingredientSynonyms = database.GetIngredientSynonyms('corn oil')
print(ingredientSynonyms)
ingredientSynonyms = database.GetIngredientSynonyms('oil')
print(ingredientSynonyms)
ingredientSynonyms = database.GetIngredientSynonyms('haggis')
print(ingredientSynonyms)

print("Adding ingredient temperature to database.")
database.AddIngredientTemperatureToIngredientIndexTable('olive oil', 'warm')
database.AddIngredientTemperatureToIngredientIndexTable('chicken', 'neutral')
database.AddIngredientTemperatureToIngredientIndexTable('spinach', 'cold')
database.AddIngredientTemperatureToIngredientIndexTable('fish', 'warm')
database.AddIngredientTemperatureToIngredientIndexTable('corn oil', 'warm')
database.AddIngredientTemperatureToIngredientIndexTable('oil', 'neutral')

print("Retrieving ingredient temperature to database.")
ingredientTemperature = database.GetIngredientTemperature('olive oil')
print(ingredientTemperature)
ingredientTemperature = database.GetIngredientTemperature('chicken')
print(ingredientTemperature)
ingredientTemperature = database.GetIngredientTemperature('spinach')
print(ingredientTemperature)
ingredientTemperature = database.GetIngredientTemperature('fish')
print(ingredientTemperature)
ingredientTemperature = database.GetIngredientTemperature('corn oil')
print(ingredientTemperature)
ingredientTemperature = database.GetIngredientTemperature('oil')
print(ingredientTemperature)
ingredientTemperature = database.GetIngredientTemperature('haggis')
print(ingredientTemperature)

print("Retrieving extended recipe IDs.")
recipeIds = database.GetExtendedRecipeIds("haggis")
print(recipeIds)
recipeIds = database.GetExtendedRecipeIds("chicken")
print(recipeIds)
recipeIds = database.GetExtendedRecipeIds("oil")
print(recipeIds)
recipeIds = database.GetExtendedRecipeIds("olive oil")
print(recipeIds)
recipeIds = database.GetExtendedRecipeIds("corn oil")
print(recipeIds)
